import Head from "next/head";
import { Hero } from "../components/Hero/Hero";
import { Features } from "../components/Features/Features";
import { Articles } from "../components/Articles/Articles";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Easybank | Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>

      <main>
        <Hero />
        <Features />
        <Articles />
      </main>
    </div>
  );
}
